# Generated by Django 4.1.1 on 2022-11-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='url_imagen',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='url_imagen',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
    ]
