# Generated by Django 4.1.1 on 2022-11-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_autor_url_imagen_libro_url_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='correo',
        ),
    ]
