# Generated by Django 4.1.1 on 2022-11-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_idioma_url_imagen_libro_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='usuario',
        ),
        migrations.AddField(
            model_name='detalle',
            name='precio_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
