# Generated by Django 4.1.1 on 2022-11-28 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_detalle_fecha_entrega_remove_detalle_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
    ]
