# Generated by Django 4.1.1 on 2022-11-28 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='libro',
        ),
    ]
