# Generated by Django 4.1.1 on 2022-11-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_detalle_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='fecha_pedido',
            field=models.DateTimeField(),
        ),
    ]
